import * as z from 'zod'
import { UuidSchema, ScenarioStatusSchema, TimestampSchema } from './common.schema.ts'
import { CharacterProgressSchema } from './character.schema.ts'

export const CampaignSchema = z.object({
  id: UuidSchema,
  /** Player-given campaign name (1-100 chars). */
  name: z.string().min(1).max(100),
  createdAt: TimestampSchema,
  updatedAt: TimestampSchema,
  /** Active party — at most 4 characters. */
  characters: z.array(CharacterProgressSchema).max(4),
  /** Scenario ID (1-17) → current status.  Keys are coerced from strings. */
  scenarioStatus: z.record(
    z.coerce.number().int().min(1).max(17),
    ScenarioStatusSchema,
  ),
  /** Ordered list of city-event IDs already drawn this campaign. */
  cityEventsDrawn: z.array(z.number().int()),
})

export type Campaign = z.infer<typeof CampaignSchema>

// ---------------------------------------------------------------------------
// Convenience: creation payload (id + timestamps auto-generated by the app)
// ---------------------------------------------------------------------------

export const CreateCampaignSchema = z.object({
  name: z.string().min(1).max(100),
})

export type CreateCampaign = z.infer<typeof CreateCampaignSchema>
